[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["corepack enable", "pnpm run build"]

[start]
cmd = "corepack enable && pnpm run start:prod"
